import type { NextPage } from "next";
import Head from "next/head";
import { PlayIcon, DocumentTextIcon } from '@heroicons/react/solid'
import Link from "next/link";

type ActionButtonProps = {
  name: string;
  description: string;
  link: string;
  icon: JSX.Element;
};

type ActionButtonIconProps = {
  icon: JSX.Element;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex flex-col items-center justify-center h-screen p-4 mx-auto">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Play <span className="text-purple-300">MÖLKKY</span>
        </h1>
        <div className="flex flex-col items-center w-full pt-3 mt-3 space-y-4 text-center lg:w-2/3">
          <ActionButton
            name="New game"
            description="Start a new round of Mölkky"
            link="/newgame"
            icon={<PlayIcon />}
          />
          <ActionButton
            name="Rules"
            description="Read the rules"
            link="/rules"
            icon={<DocumentTextIcon />}
          />
        </div>
      </main>
    </>
  );
};

const ActionButtonIcon = ({ icon }: ActionButtonIconProps) => {
  return (
    <div className="flex-shrink-0 w-8 h-8 ml-4 text-white transition-colors rounded-full group-active:text-purple-500 group-hover:text-purple-600">
      {icon}
    </div>
  )
}

const ActionButton = ({
  name,
  description,
  link,
  icon
}: ActionButtonProps) => {
  return (
    <Link href={link}>
      <a
        aria-label={description}
        className="flex items-center justify-between w-2/3 px-5 py-3 transition-colors bg-purple-600 border border-purple-600 rounded-lg hover:bg-transparent group focus:outline-none focus:ring"
      >
        <span className="font-medium text-white transition-colors group-active:text-purple-500 group-hover:text-purple-600">
          {name}
        </span>
        <ActionButtonIcon icon={icon} />
      </a>
    </Link>
  );
};



export default Home;
