import type { NextPage } from "next";
import Head from "next/head";
import { NewGame } from "../components/NewGame";
import Modal from "../components/Modal";
import { Rules } from "../components/Rules";
import { useCallback, useEffect, useState } from "react";
import { PlayIcon, DocumentTextIcon } from '@heroicons/react/solid'
import { ModalButton } from "../components/ModalButton";
//https://codesandbox.io/s/p828k6zom?fontsize=14&file=/src/components/Scenario/index.js:322-331

const Home: NextPage = () => {

  const [players, setPlayers] = useState<string[]>(["player-1"]);
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const [modalContent, setModalContent] = useState<JSX.Element>();

  const handleOpenModal = (modalContent: JSX.Element) => {
    setModalContent(modalContent)
    setModalIsOpen(true)
  }

  const handleSubmit = useCallback((newPlayers: any) => {
    setPlayers(newPlayers.map((p: any) => {
      return { 'id': p[0], 'value': p[1] }
    }))
  }, [])

  const handleCloseModal = useCallback(() => {
    setModalIsOpen(false)
  }, [])

  const handleAddPlayer = useCallback(() => {
    setPlayers([...players, `player-${players.length + 1}`])
  }, [players])

  useEffect(() => {
    setModalContent(
      <NewGame
        players={players}
        handleAddPlayers={handleAddPlayer}
        closeModal={handleCloseModal}
        handleSubmit={handleSubmit}
      />
    )
  }, [players, handleAddPlayer, handleCloseModal, handleSubmit])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex flex-col items-center justify-center h-screen p-4 mx-auto">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Play <span className="text-purple-300">MÖLKKY</span>
        </h1>
        <div className="flex flex-col items-center w-full pt-3 mt-3 space-y-4 text-center lg:w-2/3">
          <ModalButton
            name="New game"
            closeModal={handleCloseModal}
            handleOpenModal={handleOpenModal}
            modalContent={
              <NewGame
                players={players}
                handleAddPlayers={handleAddPlayer}
                closeModal={handleCloseModal}
                handleSubmit={handleSubmit}
              />
            }
            icon={<PlayIcon />}
          />
          <ModalButton
            name="Rules"
            closeModal={handleCloseModal}
            handleOpenModal={handleOpenModal}
            modalContent={<Rules />}
            icon={<DocumentTextIcon />}
          />
        </div>
        {JSON.stringify(players)}
        <Modal isOpen={modalIsOpen} closeModal={handleCloseModal}>
          {modalContent}
        </Modal>
      </main>
    </>
  );
};

export default Home;